
development:
  adapter: mysql2
  database: SolicitationManager_development
  username: root
  password: unGuessable
  host: localhost
  #port: 3306
test:
  adapter: mysql2
  database: SolicitationManager_test
  username: root
  password: unGuessable
  #port: 3306
production:
  adapter: mysql2
  database: SolicitationManager_production
  username: root
  password: unGuessable
  #port: 3306

