
development:
  adapter: mysql2
  database: todo_development
  username: root
  password: unGuessable
  host: localhost
  #port: 3306
test:
  adapter: mysql2
  database: todo_test
  username: root
  password: unGuessable
  #port: 3306
production:
  adapter: mysql2
  database: todo_production
  username: root
  password: unGuessable
  #port: 3306

